### ISSUE TITLE
info.rbのエンコードについて

### ISSUE THREAD

**Issue by wlbhiro** [gogotanaka/maxwell#1]
一部の環境にて、「 lib/sorry_yahoo_finance/info.rb 」のエンコードが原因でライブラリが終了するという事象が発生しました。
プログラムの先頭に「  # -_\- coding: utf-8 -_\-  」を記述したところ、問題無く動作しましたので、プログラム内に日本語のコメントがあるために発生していると思われます。

もし、よろしければ、修正してコミットしていただけると助かります。
どうぞよろしくお願い致します。
(行き違えや見当違いでしたら、できれば削除して下さいますようお願い致します。)

**Comment by gogotanaka** [comment]
@wlbhiro すみません返信が遅れました...！
`Ruby < 2.0` の挙動と思われるのですが、どうでしょうか（見当違いならすみません）

もしそうであれば申し訳ありません、キーワード引数などを使用しておりどちらにせよ Ruby 2.0.0+を必要としております.
